routes/web.php
<?php

use App\Http\Controllers\BannerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index']);




Route::group(['prefix' => 'dashboard'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');

    Route::resource('/banners', BannerController::class);
    Route::resource('/services', ServiceController::class);
    Route::resource('/settings', SettingController::class);
    Route::get('/setting', [FrontendController::class, 'setting'])->name('setting.hom');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Setting::latest()->paginate(10);
        return view('admin.settings.index', compact('settings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = [
            'mail' => $request->mail,
            'address' => $request->address,
            'mailbox' => $request->mailbox,
            'facebook' => $request->facebook,
            'logo' => $this->uploadImage($request->file('logo'))
        ];

        Setting::create($requestData);

        return redirect()
            ->route('settings.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        return view('admin.settings.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $requestData = [
            'mail' => $request->mail,
            'address' => $request->address,
            'mailbox' => $request->mailbox,
            'facebook' => $request->facebook,
        ];

        if ($request->hasFile('logo')) {
            $requestData['logo'] = $this->uploadImage($request->file('logo'));
        }

        $setting->update($requestData);

        return redirect()
            ->route('setting.hom')
            ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        $setting->delete();

        return redirect()
            ->route('settings.index')
            ->withMessage('Successfully Deleted');
    }

    public function uploadImage($logo)
    {
        $originalName = $logo->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        $logo->move(storage_path('/app/public/settings'), $fileName); 

        return $fileName;
    }
}

resources/views/admin/settings/create.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Setting Add</h6>
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('settings.index') }}">Settings List</a></h6>
            </div>
            <div class="card-body">
                <form action="{{ route('settings.store') }}" method="post" enctype="multipart/form-data">

                    @csrf

                    <x-forms.input type="file" name="logo" label='Logo' />

                    <x-forms.input type="email" name="mail" placeholder="Enter mail" required label="mail" />

                    <x-forms.input type="text" name="address" placeholder="Enter address" required label="address" />

                    <x-forms.input type="text" name="mailbox" placeholder="Enter mailbox" required label="mailbox" />

                    <x-forms.input type="text" name="facebook" placeholder="Enter facebook" required label="facebook" />



                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</x-master-admin>

resources/views/admin/settings/edit.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Setting Edit</h6>
            </div>
            <div class="card-body">
                <form action="{{ route('settings.update', $setting->id) }}" method="post" enctype="multipart/form-data">

                    @csrf
                    @method('patch')

                    <x-forms.input type="file" name="logo" label='Logo' />
                    <img width="100px" src="{{ asset('storage/settings/'.$setting->logo) }}" />

                    <x-forms.input type="email" name="mail" :value="old('mail', $setting->mail)" placeholder="Enter mail" required label="Mail" />

                    <x-forms.input type="text" name="address" :value="old('address', $setting->address)" placeholder="Enter address" required label="address" />

                    <x-forms.input type="text" name="mailbox" :value="old('mailbox', $setting->mailbox)" placeholder="Enter mailbox" required label="mailbox" />

                    <x-forms.input type="text" name="facebook" :value="old('facebook', $setting->facebook)" placeholder="Enter facebook" required label="facebook" />


                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</x-master-admin>

resources/views/admin/settings/index.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Settings List</h6>
                <x-forms.message />
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('settings.create') }}">Settings Add</a>
                </h6>
            </div>
            <div class="card-body">
                <div class="">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%"
                                    cellspacing="0" role="grid" aria-describedby="dataTable_info"
                                    style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable"
                                                rowspan="1" colspan="1" aria-sort="ascending"
                                                aria-label="sl: activate to sort column descending"
                                                style="width: 161px;">Sl#</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="title: activate to sort column ascending"
                                                style="width: 248px;">Title</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1"
                                                aria-label="description: activate to sort column ascending"
                                                style="width: 115px;">Description</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="button: activate to sort column ascending"
                                                style="width: 51px;">Button</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="button: activate to sort column ascending"
                                                style="width: 51px;">Button</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="logo: activate to sort column ascending"
                                                style="width: 108px;">Logo</th>
                                            <th style="width: 180px" class="sorting" tabindex="0"
                                                aria-controls="dataTable" rowspan="1" colspan="1"
                                                aria-label="Salary: activate to sort column ascending"
                                                style="width: 97px;">
                                                <center>Action</center>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th rowspan="1" colspan="1">Name</th>
                                            <th rowspan="1" colspan="1">Position</th>
                                            <th rowspan="1" colspan="1">Office</th>
                                            <th rowspan="1" colspan="1">Age</th>
                                            <th rowspan="1" colspan="1">Start date</th>
                                            <th rowspan="1" colspan="1">Start date</th>
                                            <th rowspan="1" colspan="1">
                                                <center>Action</center>
                                            </th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach ($settings as $setting)
                                            <tr class="odd">
                                                <td class="sorting_1">{{ $loop->iteration }}</td>
                                                <td>{{ $setting->mail }}</td>
                                                <td>{{ $setting->address }}</td>
                                                <td>{{ $setting->mailbox }}</td>
                                                <td>{{ $setting->facebook }}</td>
                                                <td><img width="50px"
                                                        src="{{ asset('storage/settings/' . $setting->logo) }}" /></td>
                                                <td>
                                                    <Center>
                                                        <a class="btn btn-sm btn-info"
                                                            href="{{ route('settings.show', $setting->id) }}">Show</a>
                                                        <a class="btn btn-sm btn-warning"
                                                            href="{{ route('settings.edit', $setting->id) }}">Edit</a>
                                                        <form action="{{ route('settings.destroy', $setting->id) }}"
                                                            method="post" style="display:inline">
                                                            @csrf
                                                            @method('delete')
                                                            <button class="btn btn-sm btn-danger"
                                                                onclick="return confirm('Are you sure want to delete')">Delete</button>
                                                        </form>
                                                    </Center>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-master-admin>