routes/web.php
<?php

use App\Http\Controllers\BannerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index']);




Route::group(['prefix' => 'dashboard'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');

    Route::resource('/banners', BannerController::class);
    Route::resource('/services', ServiceController::class);
    Route::resource('/settings', SettingController::class);
    Route::get('/setting', [FrontendController::class, 'setting'])->name('setting.hom');
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use Illuminate\Http\Request;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = Banner::latest()->paginate(10);
        return view('admin.banners.index', compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.banners.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = [
            'title' => $request->title,
            'description' => $request->description,
            'button' => $request->button,
            'is_active' => $request->is_active ? true : false,
            'image' => $this->uploadImage($request->file('image'))
        ];

        Banner::create($requestData);

        return redirect()
            ->route('banners.index')
            ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Banner $banner)
    {
        return view('admin.banners.edit', compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Banner $banner)
    {
        $requestData = [
            'title' => $request->title,
            'description' => $request->description,
            'button' => $request->button,
            'is_active' => $request->is_active ? true : false,
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }

        $banner->update($requestData);

        return redirect()
            ->route('banners.index')
            ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Banner $banner)
    {
        $banner->delete();

        return redirect()
            ->route('banners.index')
            ->withMessage('Successfully Deleted');
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        $image->move(storage_path('/app/public/banners'), $fileName); 

        // Image::make($image)
        //     ->resize(200, 200)
        //     ->save(storage_path() . '/app/public/banners/' . $fileName);

        return $fileName;
    }
}

resources/views/admin/banners/create.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Banner Add</h6>
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('banners.index') }}">Banner List</a></h6>
            </div>
            <div class="card-body">
                <form action="{{ route('banners.store') }}" method="post" enctype="multipart/form-data">

                    @csrf

                    <x-forms.input type="text" name="title" placeholder="Enter title" required label="Title" />

                    <x-forms.input type="text" name="description" placeholder="Enter Description" required label="Description" />

                    <x-forms.input type="text" name="button" placeholder="Enter Button" required label="Button" />

                    <x-forms.input type="file" name="image" label='Picture' />

                    @php
                        $checklist = ['Is Active'];
                    @endphp

                    <x-forms.checkbox :checklist="$checklist" />

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</x-master-admin>

resources/views/admin/banners/edit.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Banner Edit</h6>
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('banners.index') }}">Banner List</a></h6>
            </div>
            <div class="card-body">
                <form action="{{ route('banners.update', $banner->id) }}" method="post" enctype="multipart/form-data">

                    @csrf
                    @method('patch')

                    <x-forms.input type="text" name="title" :value="old('title', $banner->title)" placeholder="Enter title" required label="Title" />

                    <x-forms.input type="text" name="description" :value="old('description', $banner->description)" placeholder="Enter Description" required label="Description" />

                    <x-forms.input type="text" name="button" :value="old('button', $banner->button)" placeholder="Enter Button" required label="Button" />

                    <x-forms.input type="file" name="image" label='Picture' />
                    <img width="100px" src="{{ asset('storage/banners/'.$banner->image) }}" />

                    @php
                        $checklist = ['Is Active'];
                    @endphp

                    <x-forms.checkbox :checklist="$checklist" />

                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</x-master-admin>

resources/views/admin/banners/index.blade.php
<x-master-admin>
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between py-3">
                <h6 class="m-0 font-weight-bold text-primary">Banner List</h6>
                <x-forms.message />
                <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('banners.create') }}">Banner Add</a></h6>
            </div>
            <div class="card-body">
                <div class="">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%"
                                    cellspacing="0" role="grid" aria-describedby="dataTable_info"
                                    style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable"
                                                rowspan="1" colspan="1" aria-sort="ascending"
                                                aria-label="sl: activate to sort column descending"
                                                style="width: 30px;">S.N</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="title: activate to sort column ascending"
                                                style="width: 100px;">Title</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1"
                                                aria-label="description: activate to sort column ascending"
                                                style="width: 250px;">Description</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="button: activate to sort column ascending"
                                                style="width: 51px;">Button</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="images: activate to sort column ascending"
                                                style="width: 80px;">Images</th>
                                            <th style="width: 180px" class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                                colspan="1" aria-label="Salary: activate to sort column ascending"
                                                style="width: 97px;"><center>Action</center></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th rowspan="1" colspan="1">S.N</th>
                                            <th rowspan="1" colspan="1">Title</th>
                                            <th rowspan="1" colspan="1">Description</th>
                                            <th rowspan="1" colspan="1">Button</th>
                                            <th rowspan="1" colspan="1">Images</th>
                                            <th rowspan="1" colspan="1"><center>Action</center></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($banners as $banner)
                                        <tr class="odd">
                                            <td class="sorting_1">{{ $loop->iteration }}</td>
                                            <td>{{ $banner->title }}</td>
                                            <td>{{ $banner->description }}</td>
                                            <td>{{ $banner->button }}</td>
                                            <td><img width="50px" src="{{ asset('storage/banners/'.$banner->image) }}" /></td>
                                            <td>
                                                <Center>
                                                    <a class="btn btn-sm btn-info"
                                                        href="{{ route('banners.show', $banner->id) }}">Show</a>
                                                    <a class="btn btn-sm btn-warning"
                                                        href="{{ route('banners.edit', $banner->id) }}">Edit</a>
                                                    <form action="{{ route('banners.destroy', $banner->id) }}"
                                                        method="post" style="display:inline">
                                                        @csrf
                                                        @method('delete')
                                                        <button class="btn btn-sm btn-danger"
                                                            onclick="return confirm('Are you sure want to delete')">Delete</button>
                                                    </form>
                                                </Center>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-master-admin>